---
AWSTemplateFormatVersion: "2010-09-09"

Description: Mug Shot

Parameters:
  MugShotCodeBucketName:
    Type: String
    Description: The name for the bucket hosting validated mug shot
    Default: mug-shot-code-s3

  SubmissionMugShotBucketName:
    Type: String
    Description: The name for the bucket hosting submitted mug shot
    Default: mug-shot-submission-s3

  MugShotBucketName:
    Type: String
    Description: The name for the bucket hosting validated mug shot
    Default: mug-shot-s3

Resources:
  SubmissionMugShotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mug-shot-submission-s3
      # NotificationConfiguration:
      #   LambdaConfigurations:
      #     - Event: "s3:ObjectCreated:*"
      #       Function:
      #         Fn::Sub: ${TestFunction1.Arn}

  MugShotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MugShotBucketName

  LaunchSubmissionStateMachineFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: launchSubmissionStateMachine.zip
      Handler: launchSubmissionStateMachine.handler
      Environment:
        Variables:
          SUBMISSION_STATE_MACHINE: !Ref SubmissionStateMachine
      Role: !GetAtt LaunchSubmissionStateMachineFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  LaunchSubmissionStateMachineFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LaunchSubmissionStateMachineFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'
      - PolicyName: LaunchSubmissionStateMachineFunctionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "states:StartExecution"
            Resource: "*"

  ExtractAndValidateSubmittedFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: extractAndValidateSubmittedFile.zip
      Handler: extractAndValidateSubmittedFile.handler
      Role: !GetAtt ExtractAndValidateSubmittedFileFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  ExtractAndValidateSubmittedFileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: ExtractAndValidateSubmittedFileFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'

  DeleteSubmittedFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: deleteSubmittedFile.zip
      Handler: deleteSubmittedFile.handler
      Role: !GetAtt DeleteSubmittedFileFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  DeleteSubmittedFileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: DeleteSubmittedFileFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'
      - PolicyName: DeleteSubmittedFileFunctionPolicy
        PolicyDocument:
         Version: "2012-10-17"
         Statement:
           - Effect: Allow
             Action:
             - s3:DeleteObject
             Resource:
             - !GetAtt SubmissionMugShotBucket.Arn
             - !Join [ "", [ !GetAtt SubmissionMugShotBucket.Arn, "/*" ] ]

  SubmissionStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Hello World AWL example using an AWS Lambda function",
              "StartAt": "ExtractAndValidateSubmittedFileFunction",
              "States": {
                "ExtractAndValidateSubmittedFileFunction": {
                  "Type": "Task",
                  "Resource": "${ExtractAndValidateSubmittedFileFunctionArn}",
                  "Next": "DeleteSubmittedFileFunction"
                },
                "DeleteSubmittedFileFunction": {
                  "Type": "Task",
                  "Resource": "${DeleteSubmittedFileFunctionArn}",
                  "End": true
                }
              }
            }
          - {
              ExtractAndValidateSubmittedFileFunctionArn: !GetAtt ExtractAndValidateSubmittedFileFunction.Arn,
              DeleteSubmittedFileFunctionArn: !GetAtt DeleteSubmittedFileFunction.Arn
            }
      RoleArn: !GetAtt SubmissionStateMachineRole.Arn

  SubmissionStateMachineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - "lambda:InvokeFunction"
            Resource: "*"

Outputs:
  SubmissionMugShotBucket:
   Value: !GetAtt SubmissionMugShotBucket.Arn

  MugShotBucket:
    Value: !GetAtt MugShotBucket.Arn