---
AWSTemplateFormatVersion: "2010-09-09"

Description: Mug Shot

Parameters:
  MugShotCodeBucketName:
    Type: String
    Description: The name for the bucket hosting validated mug shot
    Default: mug-shot-code-s3

  SubmissionMugShotBucketName:
    Type: String
    Description: The name for the bucket hosting submitted mug shot
    Default: mug-shot-submission-s3

  MugShotBucketName:
    Type: String
    Description: The name for the bucket hosting validated mug shot
    Default: mug-shot-s3

Resources:
  SubmissionMugShotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mug-shot-submission-s3
      # NotificationConfiguration:
      #   LambdaConfigurations:
      #     - Event: "s3:ObjectCreated:*"
      #       Function:
      #         Fn::Sub: ${TestFunction1.Arn}

  MugShotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MugShotBucketName

  MugDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  LaunchSubmissionStateMachineFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: launchSubmissionStateMachine.zip
      Handler: launchSubmissionStateMachine.handler
      Environment:
        Variables:
          SUBMISSION_STATE_MACHINE: !Ref SubmissionStateMachine
      Role: !GetAtt LaunchSubmissionStateMachineFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  LaunchSubmissionStateMachineFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LaunchSubmissionStateMachineFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'
      - PolicyName: LaunchSubmissionStateMachineFunctionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "states:StartExecution"
            Resource: "*"

  ExtractAndValidateSubmittedFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: extractAndValidateSubmittedFile.zip
      Handler: extractAndValidateSubmittedFile.handler
      Role: !GetAtt ExtractAndValidateSubmittedFileFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  ExtractAndValidateSubmittedFileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: ExtractAndValidateSubmittedFileFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'

  CopySubmittedFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: copySubmittedFile.zip
      Handler: copySubmittedFile.handler
      Environment:
        Variables:
          MUG_SHOT_BUCKET: !Ref MugShotBucket
      Role: !GetAtt CopySubmittedFileFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  CopySubmittedFileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: CopySubmittedFileFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource:
            - arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - logs:*
            Resource:
            - '*'
      - PolicyName: CopySubmittedFileFunctionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource:
            - !GetAtt SubmissionMugShotBucket.Arn
            - !Join [ "", [ !GetAtt SubmissionMugShotBucket.Arn, "/*" ] ]
          - Effect: Allow
            Action:
            - s3:PutObject
            Resource:
            - !GetAtt MugShotBucket.Arn
            - !Join [ "", [ !GetAtt MugShotBucket.Arn, "/*" ] ]

  SaveInTableSubmittedFileInfoFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: saveInTableSubmittedFileInfo.zip
      Handler: saveInTableSubmittedFileInfo.handler
      Environment:
        Variables:
          MUG_TABLE: !Ref MugDynamoDBTable
      Role: !GetAtt SaveInTableSubmittedFileInfoFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  SaveInTableSubmittedFileInfoFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: SaveInTableSubmittedFileInfoFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'
      - PolicyName: SaveInTableSubmittedFileInfoFunctionPolicy
        PolicyDocument:
         Version: "2012-10-17"
         Statement:
           - Effect: Allow
             Action:
             - dynamodb:PutItem
             Resource: !Join [ "", [ "arn:aws:dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":table/", !Ref MugDynamoDBTable ] ]

  DeleteSubmittedFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref MugShotCodeBucketName
        S3Key: deleteSubmittedFile.zip
      Handler: deleteSubmittedFile.handler
      Role: !GetAtt DeleteSubmittedFileFunctionRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 10

  DeleteSubmittedFileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: DeleteSubmittedFileFunctionLogPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - logs:*
              Resource:
              - '*'
      - PolicyName: DeleteSubmittedFileFunctionPolicy
        PolicyDocument:
         Version: "2012-10-17"
         Statement:
           - Effect: Allow
             Action:
             - s3:DeleteObject
             Resource:
             - !GetAtt SubmissionMugShotBucket.Arn
             - !Join [ "", [ !GetAtt SubmissionMugShotBucket.Arn, "/*" ] ]

  SubmissionStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Extract Info from submitted file, save them while copying the file",
              "StartAt": "ExtractAndValidateSubmittedFileFunction",
              "States": {
                "ExtractAndValidateSubmittedFileFunction": {
                  "Type": "Task",
                  "Resource": "${ExtractAndValidateSubmittedFileFunctionArn}",
                  "Next": "SaveSubmittedFileInfo"
                },
                "SaveSubmittedFileInfo": {
                  "Type": "Parallel",
                  "Branches": [
                    {
                      "StartAt": "CopySubmittedFileFunction",
                      "States": {
                        "CopySubmittedFileFunction": {
                          "Type": "Task",
                          "Resource": "${CopySubmittedFileFunctionArn}",
                          "End": true
                        }
                      }
                    },
                    {
                      "StartAt": "SaveInTableSubmittedFileInfoFunction",
                      "States": {
                        "SaveInTableSubmittedFileInfoFunction": {
                          "Type": "Task",
                          "Resource": "${SaveInTableSubmittedFileInfoFunctionArn}",
                          "End": true
                        }
                      }
                    }
                  ],
                  "Next": "DeleteSubmittedFileFunction"
                },
                "DeleteSubmittedFileFunction": {
                  "Type": "Task",
                  "Resource": "${DeleteSubmittedFileFunctionArn}",
                  "End": true
                }
              }
            }
          - {
              ExtractAndValidateSubmittedFileFunctionArn: !GetAtt ExtractAndValidateSubmittedFileFunction.Arn,
              CopySubmittedFileFunctionArn: !GetAtt CopySubmittedFileFunction.Arn,
              SaveInTableSubmittedFileInfoFunctionArn: !GetAtt SaveInTableSubmittedFileInfoFunction.Arn,
              DeleteSubmittedFileFunctionArn: !GetAtt DeleteSubmittedFileFunction.Arn
            }
      RoleArn: !GetAtt SubmissionStateMachineRole.Arn

  SubmissionStateMachineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - "lambda:InvokeFunction"
            Resource: "*"

Outputs:
  SubmissionMugShotBucket:
   Value: !GetAtt SubmissionMugShotBucket.Arn

  MugShotBucket:
    Value: !GetAtt MugShotBucket.Arn