---
AWSTemplateFormatVersion: "2010-09-09"

Description: Mug Shot Cognito

Resources:
  MugShotCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MugShotCognitoUserPool
      AutoVerifiedAttributes:
      - email
      AliasAttributes:
      - email
      MfaConfiguration: "OFF"
      Schema:
      - Name: email
        AttributeDataType: String
        Mutable: false
        Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  MugShotCognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true

  MugShotCognitoIdentityPoolRole:
    Type: AWS::IAM::Role
    Properties:
     AssumeRolePolicyDocument:
       Version: "2012-10-17"
       Statement:
       - Effect: Allow
         Action:
         - sts:AssumeRoleWithWebIdentity
         Condition: { "ForAnyValue:StringLike": {"cognito-identity.amazonaws.com:amr": "unauthenticated" },  "StringEquals": {"cognito-identity.amazonaws.com:aud": !Ref MugShotCognitoIdentityPool}}
         Principal:
           Federated:
           - cognito-identity.amazonaws.com
     Path: "/"
     Policies:
     - PolicyName: main
       PolicyDocument:
         Version: "2012-10-17"
         Statement:
         - Effect: Allow
           Action:
           - s3:*
           - cognito-sync:*
           - cognito-identity:*
           Resource: "*"

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
     IdentityPoolId: !Ref MugShotCognitoIdentityPool
     Roles: {"unauthenticated": !GetAtt MugShotCognitoIdentityPoolRole.Arn}
